name: basesspcloud

channels:
  - conda-forge

dependencies:
  - python
  - pip
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - xgboost
  - pylint
  - boto3
  - s3fs
  - dvc
  - dvc-s3
  - pyyaml
  - xlrd
