name: basesspcloud

channels:
  - conda-forge

dependencies:
  - wheel
  - ipykernel
  - nbclient
  - nbformat
  - flake8
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - xgboost
  - pylint
  - hvac
  - boto3
  - s3fs
  - dvc
  - dvc-s3
  - pyyaml
  - pytest
  - xlrd
